### ISSUE TITLE
Limit maximum data requested from KairosDB 

### ISSUE THREAD

**Issue by arjunrn** [zalando-zmon/zmon-slo-metrics#13]
Currently, there are some failing requests to KairosDB because the size of the requested data slice is too large. That's because the app tries to fill in all the missing data since it was last updated. That could be a couple of minutes to months. This should be restricted to a maximum of a day.

@hjacobs would you agree?

**Comment by lmineiro** [comment]
sounds good to me. It would, eventually, catch up anyway, after a couple of successful batch processes.

@arjunrn want to contribute that? We have another pending release with #12

**Comment by lmineiro** [comment]
This was solved with #14 , right?

**Comment by mohabusama** [comment]
Is there something else to be added here?
https://github.com/zalando-zmon/zmon-slo-metrics/blob/master/app/slo.py#L49

**Comment by arjunrn** [comment]
I guess this issue was resolved with #14. However I did see some the same issue occur again but that was due to data being unavailable/corrupt in certain time ranges which caused the query to fail. It's unrelated to this issue and I guess this can be closed.
