### ISSUE TITLE
Custom time range for Service Level Reports

### ISSUE THREAD

**Issue by arjunrn** [zalando-zmon/zmon-slo-metrics#21]
Currently the handler which retrieves the data for the report has the time range hardcoded into it which is the past week. If the app has to support reports for larger intervals like a month or a year this handler should be able to accept a start and end data as parameters.

**Comment by lmineiro** [comment]
Is this what @mohabusama implemented with #20 ?

**Comment by arjunrn** [comment]
Nope that's for pulling the raw data from KairosDB and specifying the range there. This enhancement will be for the report generation which comes after.
