### ISSUE TITLE
Integrate Service Level Reports (SLRs) in web app

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-slo-metrics#4]
SLRs should ideally be generated and served (?) by the web application itself.

To be discussed:
- Trigger report generation lazily or not (when first requested?)
- Serve HTML from web application or push it elsewhere
- Support sending reports via email? (maybe later)

**Comment by mohabusama** [comment]
Merged with more generic #23

**Comment by mohabusama** [comment]
Resolved by #42
