### ISSUE TITLE
Delete product indicators does not work

### ISSUE THREAD

**Issue by antnascimento** [zalando-zmon/zmon-slo-metrics#79]
When editing the indicator you press delete button and you get a message error "Can't delete indicator"

**Comment by mohabusama** [comment]
Thanks for the report.

At the moment only Admins are allowed to delete resources, until a proper authorization mechanism is determined. Although the API responds with the informative message, the UI is only displaying a generic error message.

Will create an issue for the error message and will keep this one open until proper authorization is used.

**Comment by elauria** [comment]
Closing this as solved by #81
