### ISSUE TITLE
Ability to add, update or delete SLO from the UI

### ISSUE THREAD

**Issue by vibhory2j** [zalando-zmon/zmon-slo-metrics#88]
Ability to add, update or delete SLO from the UI

**Comment by elauria** [comment]
I'm guessing the UI is prob not intuitive enough and not that it was an error of some sort.

Add Objective operations are all done from the Product View in Edit mode.

Update and Delete operations are done from the Objective view (click on the objective listed in the Product view).

Delete operation is only accessible in Edit mode of the Objective View.

Let me know if this works for you, or if there are improvements to be made to the UX.
